version: '3.8'

services:
  app:
    container_name: markr-app
    command: bundle exec rackup -p 9292 -o 0.0.0.0
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_healthy
    ports: 
      - "9292:9292"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
    restart: always

  redis:
    container_name: markr-redis
    image: redis:7.0
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    restart: always
    environment:
      REDIS_MAXMEMORY: 512mb
      REDIS_APPENDONLY: "yes"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  gem_cache:
  redis-data:
