version: '3'
services:
  app:
    container_name: markr-app
    command: bundle exec rackup -p 9292 -o 0.0.0.0
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports: 
      - "9292:9292"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
    env_file: ./config/.env
    restart: always

  redis:
    container_name: markr-redis
    image: redis:latest
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    restart: always
    environment:
      REDIS_MAXMEMORY: 512mb
      REDIS_APPENDONLY: "yes"

volumes:
  gem_cache:
  redis-data:
